### ISSUE TITLE
i can't install in Laravel 5.2

### ISSUE THREAD

**Issue by josuegomez** [Arkitecht/fedex-laravel#1]
i run : composer require arkitecht/fedex-laravel

i this is the error
`
  [InvalidArgumentException]                                                                          
  Could not find package arkitecht/fedex-laravel at any version for your minimum-stability (stable).  
   Check the package spelling or your minimum-stability   
`

**Comment by josuegomez** [comment]
solved if i put on the requiere

        "arkitecht/fedex-php":"dev-master",
        "wsdltophp/packagebase":"dev-master",
        "arkitecht/fedex-laravel":"@dev"

**Comment by edwinricaurte** [comment]
Works with Production Key Only.

**Comment by Arkitecht** [comment]
@edwinricaurte  Did you set the FEDEX_USE_BETA flag?
